### ISSUE TITLE
[Feature request] Allow detect major version from branch name

### ISSUE THREAD

**Issue by bvis** [softonic/ci-version#2]
Currently this package detects the major version to use as a reference from composer.json and package.json files, but it would be great to allow to get it from the branch name. For example:

If branch name is `release/v3`, `release/v3.x` or `release/3.x`, that typically used for this purpose. It could be called with the parameters:
```
docker run --rm -v /path/to/my/repository:/repo:ro softonic/ci-version --compatible-with git-branching
```

**Comment by rubennorte** [comment]
That could work. I'd also add an option like `--branch-regex 'release/v([0-9.]+)'`.

Would you consider creating a PR for this?

**Comment by rubennorte** [comment]
I was just thinking that you could use the `composer.json` or `package.json` to do so. Just set the proper version in the file for each branch and it'll work fine.

I'm closing the issue. Feel free to reopen if you consider is necessary.
