### ISSUE TITLE
--compatible-with option doesn't work always as expected

### ISSUE THREAD

**Issue by nachovalen** [softonic/ci-version#4]
executing: ci-version --compatible-with package.json
use case:
 Current commit tags: <none>
  All tags: 0.1.0 0.2.0 0.3.0
  package.json/composer.json: 0.1.0
  => New version: 0.2.0

We think new version should be 0.4.0 instead.

We found a possible solution modifying in createCompatibleVersion method the "compatibleWith" rang
If you agree this is an unexpected behaviour, we can submit a PR.

Thanks!

**Comment by bvis** [comment]
Let's open the PR, then.

**Comment by bvis** [comment]
It should have been closed with the related PR.
